version: '3.7'

services:

  mongo:
    image: mongo:latest
    command: --serviceExecutor adaptive
    volumes:
      # allows mongo data to persist regardless of container state
      - mongo_data:/data/db
    restart: always
    ports:
       - 27017:27017
    environment:
      MONGO_INITDB_DATABASE: testdatastore
    networks:
      - webnet

  node:
    image: node:8-alpine
    user: "node"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=production
    volumes:
      - ./:/home/node/app
    expose:
      - "8081"
      - "12700"
    command: "npm start"
    networks:
      - webnet

  api:
    # replace username/repo:tag with your name and image details
    # https://hub.docker.com/r/caselletuckelle/test-data-store
    image: caselletuckelle/test-data-store:latest
    depends_on:
      - node
      - mongo
    ports:
      - "12700:12700"
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
    networks:
      - webnet
    command: "npm run server"

networks:
  webnet:

volumes:
  mongo_data:
