version: '3.1'

services:

  mongo:
    image: mongo:latest
    command: --serviceExecutor adaptive
    volumes:
      # allows mongo data to persist regardless of container state
      - mongo_data:/data/db
    restart: always
    ports:
       - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: testdatastore
    networks:
      - webnet

  mongo-express:
    image: mongo-express
    depends_on:
      - mongo
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
    networks:
      - webnet

  node:
    image: node:8-alpine
    user: node
    working_dir: /home/node/app
    environment:
      - NODE_ENV=production
    volumes:
      - ./:/home/node/app
    expose:
      - "8081"
      - "12700"
    command: "npm start"
    networks:
      - webnet

  api_dev_env:
    # image will only be created and run for development use locally
    image: test-data-store:dev
    depends_on:
      - node
      - mongo
    ports:
      - "12700:12700"
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
    volumes:
      # mounted drive allows realtime development to app code base
      - ./:/app
    networks:
      - webnet
    command: "npm run server"

networks:
  webnet:

volumes:
  mongo_data:
